a = input("Digite um valor: ")
print('O tipo primitivo desse valor é ', type(a))
print('Contém somente espaços? ', a.isspace())
print('É um número? ', a.isnumeric())
print('É alfabético? ', a.isalpha())
print('É alfanumérico? ', a.isalnum())
print('Está em caixa alta? ', a.isupper())
print('Está em caixa baixa? ', a.islower())
print('Está capitalizada? ', a.istitle())
